### ISSUE TITLE
Update! does not work with non-integer ids

### ISSUE THREAD

**Issue by AndreTheHunter** [metabase/toucan#20]
@camsaul

When testing my application I get at `java.lang.AssertionError: Assert failed: (integer? id)` for `toucan.db/update!`. The `:pre` condition assumes the id is integer, however we use UUIDs.

I've created a PR: https://github.com/metabase/toucan/pull/19

Also, I can not run the tests locally. I get a `org.postgresql.util.PSQLException: The server requested password-based authentication, but no password was provided.` error. I think a local testing db is needed (a `toucan_test` database?). I'd recommend setting up a [global fixture](https://github.com/circleci/circleci.test#global-fixtures) that creates the db if required.

Also, switch to CircleCI 2.0 https://circleci.com/docs/2.0/migrating-from-1-2/, then the same docker container used for the testing database could be run locally.

**Comment by camsaul** [comment]
Merged your PR. Thanks for the contribution!

**Comment by camsaul** [comment]
@AndreTheHunter I went ahead and tweaked the test code as well so you can configure the DB connection https://github.com/metabase/toucan#tests--linting

You should be able to run tests locally now
