### ISSUE TITLE
Setting :identifiers for JDBC connection is broken with toucan.db/query in 1.13.0

### ISSUE THREAD

**Issue by miikka** [metabase/toucan#60]
We're setting `:identifiers` for our JDBC connection to a function that converts underscores to dashes. However, Toucan 1.13.0 introduced [the this change][change] to `toucan.db/query` which overrides our identifiers function.

[change]: https://github.com/metabase/toucan/commit/c86fb15f4a5a78ac9f60df942aa4ff223a460e2a#diff-a3cc93252c3ced20f3cc89c0c0bfd746R274-R278

Now our underscores do not get transformed to dashes, which of course breaks many things, and there's no workaround. I think that the best thing would be to not set `:identifiers` here and just let `clojure.java.jdbc` handle it once the version with the fix has been released.

@camsaul

**Comment by camsaul** [comment]
@miikka would it fix things for you if I changed

```clj
(into options {:identifiers u/lower-case}
```

to 

```clj
(merge {:identifiers u/lower-case} options)
```

That way if `options` specifies `:identifiers` it will override the default we added

**Comment by miikka** [comment]
The trouble is that we set `:identifiers` already in the JDBC connection map, i.e. what is returned by `(connection)`. This way we do not need to pass it to every `db/query` invocation in the codebase. What you propose would still break our code, because the third parameter to `jdbc/query` would still be `{:identifiers u/lower-case}` be default. But like you say, at least it does allow the workaround by passing in options every time.
