### ISSUE TITLE
Allow extending protocols right from defmodel

### ISSUE THREAD

**Issue by plexus** [metabase/toucan#9]
The current way of specifying hydration keys is rather unwieldy, so I came up with this

``` clojure
(defmodel Video :videos
  models/IModel
  (hydration-keys [_]
    [:video :preview_video]))
```

I have a working patch (see [this gist](https://gist.github.com/3b58aba0861bd5358fc71c6f4cce5fa3)). Happy to submit it, just wanted to check first if this is something you'd be interested in.

**Comment by camsaul** [comment]
@plexus, sure. There's no reason not to support something like this

**Comment by camsaul** [comment]
If you submitted a PR do you think you could update the dox as well to include both ways of doing things?

**Comment by plexus** [comment]
ok, I can do that.
