### ISSUE TITLE
Add ns qualified keyword options to IModel

### ISSUE THREAD

**Issue by bolivier** [metabase/toucan#96]
@camsaul 

Qualified keywords are pretty common in Clojure, and either inferring them from table names or providing them per-model would be nice to have. 

I'm using next.jdbc right now, and it's handling a lot of that for me.

**Comment by camsaul** [comment]
Hi @bolivier, I'm currently working on [Toucan 2](https://github.com/camsaul/toucan2). It's pretty close to being ready for use (and I still need to write a lot of documentation) but I'm planning on adding namespaced keyword support there. Toucan 2 uses `next.jdbc` and Honey SQL 2 under the hood

**Comment by bolivier** [comment]
@camsaul Very cool!  

Let me know if you're looking for any help; I'd love to contribute what I can :slightly_smiling_face:
